[package]
name = "taiko-wiki-data-analysis"
version = "0.1.0"
authors = ["TonalidadeHidrica"]
edition = "2018"

[dependencies]
reqwest = "0.10.4"
futures = "0.3.4"
tokio = { version = "0.2.13", features = ["macros"] }
scraper = "0.11.0"
