name: Download dump data of taiko-wiki
on:
  schedule:
    - cron: '0 19 * * *'
  # push:
  #   branches:
  #     - master

jobs:
  build:
    name: Download wiki data
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Determine the filename to save
        run: "echo save_file_name=taiko-wiki-dump-`date '+%Y%m%d-%H%M%S'`.tar.gz >> $GITHUB_ENV"

      - name: View env value
        run: echo $save_file_name

      - name: Execute download
        run: cargo run --bin download-backup --release

      # - name: Compress the result as .tar.gz
      #   run: tar zcf ${{ env.save_file_name }} dump-data

      - name: Upload generated file
        uses: actions/upload-artifact@v1
        with:
          name: $save_file_name
          path: dump-data
